<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AddonSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('addon_settings')->delete();
        
        \DB::table('addon_settings')->insert(array (
            0 => 
            array (
                'id' => '070c6bbd-d777-11ed-96f4-0c7a158e4469',
                'key_name' => 'twilio',
                'live_values' => '{"gateway":"twilio","mode":"live","status":0,"sid":"","messaging_service_sid":"","token":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"twilio","mode":"live","status":0,"sid":"","messaging_service_sid":"","token":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-10 04:14:44',
                'additional_data' => NULL,
            ),
            1 => 
            array (
                'id' => '070c766c-d777-11ed-96f4-0c7a158e4469',
                'key_name' => '2factor',
                'live_values' => '{"gateway":"2factor","mode":"live","status":"0","api_key":""}',
                'test_values' => '{"gateway":"2factor","mode":"live","status":"0","api_key":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-10 05:17:06',
                'additional_data' => NULL,
            ),
            2 => 
            array (
                'id' => '0d8a9308-d6a5-11ed-962c-0c7a158e4469',
                'key_name' => 'mercadopago',
                'live_values' => '{"gateway":"mercadopago","mode":"live","status":1,"access_token":"","public_key":""}',
                'test_values' => '{"gateway":"mercadopago","mode":"live","status":1,"access_token":"","public_key":""}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-12 05:37:50',
                'additional_data' => '{"gateway_title":"Mercadopago","gateway_image":null}',
            ),
            3 => 
            array (
                'id' => '0d8a9e49-d6a5-11ed-962c-0c7a158e4469',
                'key_name' => 'liqpay',
                'live_values' => '{"gateway":"liqpay","mode":"live","status":"1","private_key":null,"public_key":null}',
                'test_values' => '{"gateway":"liqpay","mode":"live","status":"1","private_key":null,"public_key":null}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '{"gateway_title":"Liqpay","gateway_image":null}',
            ),
            4 => 
            array (
                'id' => '101befdf-d44b-11ed-8564-0c7a158e4469',
                'key_name' => 'paypal',
                'live_values' => '{"gateway":"paypal","mode":"live","status":"0","client_id":null,"client_secret":null}',
                'test_values' => '{"gateway":"paypal","mode":"live","status":"0","client_id":null,"client_secret":null}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '{"gateway_title":"Paypal","gateway_image":null}',
            ),
            5 => 
            array (
                'id' => '133d9647-cabb-11ed-8fec-0c7a158e4469',
                'key_name' => 'hyper_pay',
                'live_values' => '{"gateway":"hyper_pay","mode":"live","status":"0","entity_id":"","access_code":""}',
                'test_values' => '{"gateway":"hyper_pay","mode":"live","status":"0","entity_id":"","access_code":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-09 00:59:22',
                'additional_data' => NULL,
            ),
            6 => 
            array (
                'id' => '1821029f-d776-11ed-96f4-0c7a158e4469',
                'key_name' => 'msg91',
                'live_values' => '{"gateway":"msg91","mode":"live","status":0,"template_id":"","auth_key":""}',
                'test_values' => '{"gateway":"msg91","mode":"live","status":0,"template_id":"","auth_key":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-10 04:14:44',
                'additional_data' => NULL,
            ),
            7 => 
            array (
                'id' => '18210f2b-d776-11ed-96f4-0c7a158e4469',
                'key_name' => 'nexmo',
                'live_values' => '{"gateway":"nexmo","mode":"live","status":"0","api_key":"","api_secret":"","token":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"nexmo","mode":"live","status":"0","api_key":"","api_secret":"","token":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-10 04:14:44',
                'additional_data' => NULL,
            ),
            8 => 
            array (
                'id' => '18fbb21f-d6ad-11ed-962c-0c7a158e4469',
                'key_name' => 'foloosi',
                'live_values' => '{"gateway":"foloosi","mode":"live","status":"0","merchant_key":""}',
                'test_values' => '{"gateway":"foloosi","mode":"test","status":"0","merchant_key":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            9 => 
            array (
                'id' => '2767d142-d6a1-11ed-962c-0c7a158e4469',
                'key_name' => 'paytm',
                'live_values' => '{"gateway":"paytm","mode":"live","status":"1","merchant_key":null,"merchant_id":null,"merchant_website_link":null}',
                'test_values' => '{"gateway":"paytm","mode":"live","status":"1","merchant_key":null,"merchant_id":null,"merchant_website_link":null}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '{"gateway_title":"Paytm","gateway_image":null}',
            ),
            10 => 
            array (
                'id' => '3201d2e6-c937-11ed-a424-0c7a158e4469',
                'key_name' => 'amazon_pay',
                'live_values' => '{"gateway":"amazon_pay","mode":"test","status":"0","pass_phrase": "","access_code": "","merchant_identifier": ""}',
                'test_values' => '{"gateway":"amazon_pay","mode":"test","status":"0","pass_phrase": "","access_code": "","merchant_identifier": ""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            11 => 
            array (
                'id' => '4593b25c-d6a1-11ed-962c-0c7a158e4469',
                'key_name' => 'paytabs',
                'live_values' => '{"gateway":"paytabs","mode":"live","status":"1","profile_id":null,"server_key":null,"base_url":null}',
                'test_values' => '{"gateway":"paytabs","mode":"live","status":"1","profile_id":null,"server_key":null,"base_url":null}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-09 04:23:25',
                'additional_data' => '{"gateway_title":"Paytabs","gateway_image":null}',
            ),
            12 => 
            array (
                'id' => '4e9b8dfb-e7d1-11ed-a559-0c7a158e4469',
                'key_name' => 'bkash',
                'live_values' => '{"gateway":"bkash","mode":"live","status":"1","app_key":"5tunt4masn6pv2hnvte1sb5n3j","app_secret":"1vggbqd4hqk9g96o9rrrp2jftvek578v7d2bnerim12a87dbrrka","username":"sandboxTestUser","password":"hWD@8vtzw0"}',
                'test_values' => '{"gateway":"bkash","mode":"live","status":"1","app_key":"5tunt4masn6pv2hnvte1sb5n3j","app_secret":"1vggbqd4hqk9g96o9rrrp2jftvek578v7d2bnerim12a87dbrrka","username":"sandboxTestUser","password":"hWD@8vtzw0"}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-09 01:08:40',
                'additional_data' => '{"gateway_title":"Bkash","gateway_image":null}',
            ),
            13 => 
            array (
                'id' => '544a24a4-c872-11ed-ac7a-0c7a158e4469',
                'key_name' => 'fatoorah',
                'live_values' => '{"gateway":"fatoorah","mode":"live","status":"0","api_key":""}',
                'test_values' => '{"gateway":"fatoorah","mode":"test","status":"0","api_key":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            14 => 
            array (
                'id' => '58c1bc8a-d6ac-11ed-962c-0c7a158e4469',
                'key_name' => 'ccavenue',
                'live_values' => '{"gateway":"ccavenue","mode":"test","status":"0","merchant_id":"","working_key":"","access_code":""}',
                'test_values' => '{"gateway":"ccavenue","mode":"test","status":"0","merchant_id":"","working_key":"","access_code":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-13 00:24:16',
                'additional_data' => '{"gateway_title":"","gateway_image":""}',
            ),
            15 => 
            array (
                'id' => '5e2d2ef9-d6ab-11ed-962c-0c7a158e4469',
                'key_name' => 'thawani',
                'live_values' => '{"gateway":"thawani","mode":"live","status":"0","public_key":"","private_key":""}',
                'test_values' => '{"gateway":"thawani","mode":"live","status":"0","public_key":"","private_key":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-13 01:14:00',
                'additional_data' => '{"gateway_title":"","gateway_image":""}',
            ),
            16 => 
            array (
                'id' => '60cc83cc-d5b9-11ed-b56f-0c7a158e4469',
                'key_name' => 'sixcash',
                'live_values' => '{"gateway":"sixcash","mode":"test","status":"0","public_key":"","secret_key":"","merchant_number":"", "base_url":""}',
                'test_values' => '{"gateway":"sixcash","mode":"test","status":"0","public_key":"","secret_key":"","merchant_number":"", "base_url":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-12 05:18:06',
                'additional_data' => '{"gateway_title":"","gateway_image":""}',
            ),
            17 => 
            array (
                'id' => '68579846-d8e8-11ed-8249-0c7a158e4469',
                'key_name' => 'alphanet_sms',
                'live_values' => '{"gateway":"alphanet_sms","mode":"live","status":0,"api_key":"","otp_template":""}',
                'test_values' => '{"gateway":"alphanet_sms","mode":"live","status":0,"api_key":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            18 => 
            array (
                'id' => '6857a2e8-d8e8-11ed-8249-0c7a158e4469',
                'key_name' => 'sms_to',
                'live_values' => '{"gateway":"sms_to","mode":"live","status":0,"api_key":"","sender_id":"","otp_template":""}',
                'test_values' => '{"gateway":"sms_to","mode":"live","status":0,"api_key":"","sender_id":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            19 => 
            array (
                'id' => '74c30c00-d6a6-11ed-962c-0c7a158e4469',
                'key_name' => 'hubtel',
                'live_values' => '{"gateway":"hubtel","mode":"live","status":"0","account_number":"","api_id":"","api_key":""}',
                'test_values' => '{"gateway":"hubtel","mode":"test","status":"0","account_number":"","api_id":"","api_key":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            20 => 
            array (
                'id' => '74e46b0a-d6aa-11ed-962c-0c7a158e4469',
                'key_name' => 'tap',
                'live_values' => '{"gateway":"tap","mode":"live","status":"0","secret_key":""}',
                'test_values' => '{"gateway":"tap","mode":"test","status":"0","secret_key":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            21 => 
            array (
                'id' => '761ca96c-d1eb-11ed-87ca-0c7a158e4469',
                'key_name' => 'swish',
                'live_values' => '{"gateway":"swish","mode":"test","status":"0","number": ""}',
                'test_values' => '{"gateway":"swish","mode":"test","status":"0","number": ""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            22 => 
            array (
                'id' => '7b1c3c5f-d2bd-11ed-b485-0c7a158e4469',
                'key_name' => 'payfast',
                'live_values' => '{"gateway":"payfast","mode":"test","status":"0","merchant_id":"","secured_key":""}',
                'test_values' => '{"gateway":"payfast","mode":"test","status":"0","merchant_id":"","secured_key":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            23 => 
            array (
                'id' => '8592417b-d1d1-11ed-a984-0c7a158e4469',
                'key_name' => 'esewa',
                'live_values' => '{"gateway":"esewa","mode":"test","status":"0","merchantCode": ""}',
                'test_values' => '{"gateway":"esewa","mode":"test","status":"0","merchantCode": "EPAYTEST"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            24 => 
            array (
                'id' => '9162a1dc-cdf1-11ed-affe-0c7a158e4469',
                'key_name' => 'viva_wallet',
                'live_values' => '{"gateway":"viva_wallet","mode":"test","status":"0","client_id": "","client_secret": ""}
',
                'test_values' => '{"gateway":"viva_wallet","mode":"test","status":"0","client_id": "","client_secret": ""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            25 => 
            array (
                'id' => '998ccc62-d6a0-11ed-962c-0c7a158e4469',
                'key_name' => 'stripe',
                'live_values' => '{"gateway":"stripe","mode":"live","status":"0","api_key":null,"published_key":null}',
                'test_values' => '{"gateway":"stripe","mode":"live","status":"0","api_key":null,"published_key":null}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-13 00:26:31',
                'additional_data' => '{"gateway_title":"Stripe","gateway_image":null}',
            ),
            26 => 
            array (
                'id' => 'a3313755-c95d-11ed-b1db-0c7a158e4469',
                'key_name' => 'iyzi_pay',
                'live_values' => '{"gateway":"iyzi_pay","mode":"test","status":"0","api_key": "","secret_key": "","base_url": ""}',
                'test_values' => '{"gateway":"iyzi_pay","mode":"test","status":"0","api_key": "","secret_key": "","base_url": ""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            27 => 
            array (
                'id' => 'a76c8993-d299-11ed-b485-0c7a158e4469',
                'key_name' => 'momo',
                'live_values' => '{"gateway":"momo","mode":"live","status":"0","api_key":"","api_user":"","subscription_key":""}',
                'test_values' => '{"gateway":"momo","mode":"live","status":"0","api_key":"","api_user":"","subscription_key":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-09 00:39:19',
                'additional_data' => NULL,
            ),
            28 => 
            array (
                'id' => 'a8608119-cc76-11ed-9bca-0c7a158e4469',
                'key_name' => 'moncash',
                'live_values' => '{"gateway":"moncash","mode":"test","status":"0","client_id":"","secret_key": ""}
',
                'test_values' => '{"gateway":"moncash","mode":"test","status":"0","client_id":"","secret_key": ""}
',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            29 => 
            array (
                'id' => 'ad5af1c1-d6a2-11ed-962c-0c7a158e4469',
                'key_name' => 'razor_pay',
                'live_values' => '{"gateway":"razor_pay","mode":"live","status":"0","api_key":null,"api_secret":null}',
                'test_values' => '{"gateway":"razor_pay","mode":"live","status":"0","api_key":null,"api_secret":null}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '{"gateway_title":"Razor pay","gateway_image":null}',
            ),
            30 => 
            array (
                'id' => 'ad5b02a0-d6a2-11ed-962c-0c7a158e4469',
                'key_name' => 'senang_pay',
                'live_values' => '{"gateway":"senang_pay","mode":"live","status":"1","callback_url":null,"secret_key":null,"merchant_id":null}',
                'test_values' => '{"gateway":"senang_pay","mode":"live","status":"1","callback_url":null,"secret_key":null,"merchant_id":null}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '{"gateway_title":"Senang pay","gateway_image":null}',
            ),
            31 => 
            array (
                'id' => 'b6c333f6-d8e9-11ed-8249-0c7a158e4469',
                'key_name' => 'akandit_sms',
                'live_values' => '{"gateway":"akandit_sms","mode":"live","status":0,"username":"","password":"","otp_template":""}',
                'test_values' => '{"gateway":"akandit_sms","mode":"live","status":0,"username":"","password":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            32 => 
            array (
                'id' => 'b6c33c87-d8e9-11ed-8249-0c7a158e4469',
                'key_name' => 'global_sms',
                'live_values' => '{"gateway":"global_sms","mode":"live","status":0,"user_name":"","password":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"global_sms","mode":"live","status":0,"user_name":"","password":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            33 => 
            array (
                'id' => 'b8992bd4-d6a0-11ed-962c-0c7a158e4469',
                'key_name' => 'paymob_accept',
                'live_values' => '{"gateway":"paymob_accept","mode":"live","status":"0","callback_url":null,"api_key":null,"iframe_id":null,"integration_id":null,"hmac":null}',
                'test_values' => '{"gateway":"paymob_accept","mode":"live","status":"0","callback_url":null,"api_key":null,"iframe_id":null,"integration_id":null,"hmac":null}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '{"gateway_title":"Paymob accept","gateway_image":null}',
            ),
            34 => 
            array (
                'id' => 'c41c0dcd-d119-11ed-9f67-0c7a158e4469',
                'key_name' => 'maxicash',
                'live_values' => '{"gateway":"maxicash","mode":"test","status":"0","merchantId": "","merchantPassword": ""}',
                'test_values' => '{"gateway":"maxicash","mode":"test","status":"0","merchantId": "","merchantPassword": ""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            35 => 
            array (
                'id' => 'c9249d17-cd60-11ed-b879-0c7a158e4469',
                'key_name' => 'pvit',
                'live_values' => '{"gateway":"pvit","mode":"test","status":"0","mc_tel_merchant": "","access_token": "", "mc_merchant_code": ""}',
                'test_values' => '{"gateway":"pvit","mode":"test","status":"0","mc_tel_merchant": "","access_token": "", "mc_merchant_code": ""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            36 => 
            array (
                'id' => 'cb0081ce-d775-11ed-96f4-0c7a158e4469',
                'key_name' => 'releans',
                'live_values' => '{"gateway":"releans","mode":"live","status":0,"api_key":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"releans","mode":"live","status":0,"api_key":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-04-10 04:14:44',
                'additional_data' => NULL,
            ),
            37 => 
            array (
                'id' => 'd4f3f5f1-d6a0-11ed-962c-0c7a158e4469',
                'key_name' => 'flutterwave',
                'live_values' => '{"gateway":"flutterwave","mode":"live","status":1,"secret_key":"FLWSECK_TEST-ec27426eb062491500a9eb95723b5436-X","public_key":"FLWPUBK_TEST-3f6a0b6c3d621c4ecbb9beeff516c92b-X","hash":"FLWSECK_TEST951e36220f66"}',
                'test_values' => '{"gateway":"flutterwave","mode":"live","status":1,"secret_key":"FLWSECK_TEST-ec27426eb062491500a9eb95723b5436-X","public_key":"FLWPUBK_TEST-3f6a0b6c3d621c4ecbb9beeff516c92b-X","hash":"FLWSECK_TEST951e36220f66"}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '{"gateway_title":"Flutterwave","gateway_image":null}',
            ),
            38 => 
            array (
                'id' => 'd822f1a5-c864-11ed-ac7a-0c7a158e4469',
                'key_name' => 'paystack',
                'live_values' => '{"gateway":"paystack","mode":"live","status":"0","callback_url":null,"public_key":null,"secret_key":null,"merchant_email":null}',
                'test_values' => '{"gateway":"paystack","mode":"live","status":"0","callback_url":null,"public_key":null,"secret_key":null,"merchant_email":null}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => '{"gateway_title":"Paystack","gateway_image":null}',
            ),
            39 => 
            array (
                'id' => 'daec8d59-c893-11ed-ac7a-0c7a158e4469',
                'key_name' => 'xendit',
                'live_values' => '{"gateway":"xendit","mode":"test","status":"0","api_key":""}',
                'test_values' => '{"gateway":"xendit","mode":"test","status":"0","api_key":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            40 => 
            array (
                'id' => 'dc0f5fc9-d6a5-11ed-962c-0c7a158e4469',
                'key_name' => 'worldpay',
                'live_values' => '{"gateway":"worldpay","mode":"live","status":"0","OrgUnitId":"","jwt_issuer":"","mac":"","merchantCode":"","xml_password":""}',
                'test_values' => '{"gateway":"worldpay","mode":"test","status":"0","OrgUnitId":"","jwt_issuer":"","mac":"","merchantCode":"","xml_password":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            41 => 
            array (
                'id' => 'e0450278-d8eb-11ed-8249-0c7a158e4469',
                'key_name' => 'signal_wire',
                'live_values' => '{"gateway":"signal_wire","mode":"live","status":0,"project_id":"","token":"","space_url":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"signal_wire","mode":"live","status":0,"project_id":"","token":"","space_url":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            42 => 
            array (
                'id' => 'e0450b40-d8eb-11ed-8249-0c7a158e4469',
                'key_name' => 'paradox',
                'live_values' => '{"gateway":"paradox","mode":"live","status":0,"api_key":""}',
                'test_values' => '{"gateway":"paradox","mode":"live","status":0,"api_key":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            43 => 
            array (
                'id' => 'ea346efe-cdda-11ed-affe-0c7a158e4469',
                'key_name' => 'ssl_commerz',
                'live_values' => '{"gateway":"ssl_commerz","mode":"live","status":"0","store_id":null,"store_password":null}',
                'test_values' => '{"gateway":"ssl_commerz","mode":"live","status":"0","store_id":null,"store_password":null}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => '2023-07-31 16:14:48',
                'additional_data' => '{"gateway_title":"Ssl commerz","gateway_image":null}',
            ),
            44 => 
            array (
                'id' => 'eed88336-d8ec-11ed-8249-0c7a158e4469',
                'key_name' => 'hubtel',
                'live_values' => '{"gateway":"hubtel","mode":"live","status":0,"sender_id":"","client_id":"","client_secret":"","otp_template":""}',
                'test_values' => '{"gateway":"hubtel","mode":"live","status":0,"sender_id":"","client_id":"","client_secret":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            45 => 
            array (
                'id' => 'f149c546-d8ea-11ed-8249-0c7a158e4469',
                'key_name' => 'viatech',
                'live_values' => '{"gateway":"viatech","mode":"live","status":0,"api_url":"","api_key":"","sender_id":"","otp_template":""}',
                'test_values' => '{"gateway":"viatech","mode":"live","status":0,"api_url":"","api_key":"","sender_id":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
            46 => 
            array (
                'id' => 'f149cd9c-d8ea-11ed-8249-0c7a158e4469',
                'key_name' => '019_sms',
                'live_values' => '{"gateway":"019_sms","mode":"live","status":0,"password":"","username":"","username_for_token":"","sender":"","otp_template":""}',
                'test_values' => '{"gateway":"019_sms","mode":"live","status":0,"password":"","username":"","username_for_token":"","sender":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'additional_data' => NULL,
            ),
        ));
        
        
    }
}