<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $this->call(ModulesTableSeeder::class);
        $this->call(AdminsTableSeeder::class);
        $this->call(AccountTransactionsTableSeeder::class);
        $this->call(AddonSettingsTableSeeder::class);
        $this->call(AddOnsTableSeeder::class);
        $this->call(AdminFeaturesTableSeeder::class);
        $this->call(AdminPromotionalBannersTableSeeder::class);
        $this->call(AdminRolesTableSeeder::class);
        $this->call(AdminSpecialCriteriasTableSeeder::class);
        $this->call(AdminTestimonialsTableSeeder::class);
        $this->call(AdminWalletsTableSeeder::class);
        $this->call(AttributesTableSeeder::class);
        $this->call(BannersTableSeeder::class);
        $this->call(BusinessSettingsTableSeeder::class);
        $this->call(CampaignsTableSeeder::class);
        $this->call(CampaignStoreTableSeeder::class);
        $this->call(CartsTableSeeder::class);
        $this->call(CategoriesTableSeeder::class);
        $this->call(CommonConditionsTableSeeder::class);
        $this->call(ContactsTableSeeder::class);
        $this->call(ConversationsTableSeeder::class);
        $this->call(CouponsTableSeeder::class);
        $this->call(CurrenciesTableSeeder::class);
        $this->call(CustomerAddressesTableSeeder::class);
        $this->call(DataSettingsTableSeeder::class);
        $this->call(DeliveryHistoriesTableSeeder::class);
        $this->call(DeliveryManWalletsTableSeeder::class);
        $this->call(DeliveryMenTableSeeder::class);
        $this->call(DisbursementsTableSeeder::class);
        $this->call(DisbursementDetailsTableSeeder::class);
        $this->call(DisbursementWithdrawalMethodsTableSeeder::class);
        $this->call(DiscountsTableSeeder::class);
        $this->call(DMReviewsTableSeeder::class);
        $this->call(DMVehiclesTableSeeder::class);
        $this->call(EmailTemplatesTableSeeder::class);
        $this->call(EmailVerificationsTableSeeder::class);
        $this->call(EmployeeRolesTableSeeder::class);
        $this->call(ExpensesTableSeeder::class);
        $this->call(FailedJobsTableSeeder::class);
        $this->call(FlashSalesTableSeeder::class);
        $this->call(FlashSaleItemsTableSeeder::class);
        $this->call(FlutterSpecialCriteriasTableSeeder::class);
        $this->call(GuestsTableSeeder::class);
        $this->call(ItemsTableSeeder::class);
        $this->call(ItemCampaignsTableSeeder::class);
        $this->call(ItemTagTableSeeder::class);
        $this->call(JobsTableSeeder::class);
        $this->call(LoyaltyPointTransactionsTableSeeder::class);
        $this->call(MessagesTableSeeder::class);
        $this->call(MigrationsTableSeeder::class);
        $this->call(ModuleTypesTableSeeder::class);
        $this->call(ModuleWiseBannersTableSeeder::class);
        $this->call(ModuleWiseWhyChoosesTableSeeder::class);
        $this->call(ModuleZoneTableSeeder::class);
        $this->call(NewslettersTableSeeder::class);
        $this->call(NotificationsTableSeeder::class);
        $this->call(NotificationMessagesTableSeeder::class);
        $this->call(OauthAccessTokensTableSeeder::class);
        $this->call(OauthAuthCodesTableSeeder::class);
        $this->call(OauthClientsTableSeeder::class);
        $this->call(OauthPersonalAccessClientsTableSeeder::class);
        $this->call(OauthRefreshTokensTableSeeder::class);
        $this->call(OfflinePaymentsTableSeeder::class);
        $this->call(OfflinePaymentMethodsTableSeeder::class);
        $this->call(OrdersTableSeeder::class);
        $this->call(OrderCancelReasonsTableSeeder::class);
        $this->call(OrderDeliveryHistoriesTableSeeder::class);
        $this->call(OrderDetailsTableSeeder::class);
        $this->call(OrderPaymentsTableSeeder::class);
        $this->call(OrderTransactionsTableSeeder::class);
        $this->call(ParcelCategoriesTableSeeder::class);
        $this->call(ParcelDeliveryInstructionsTableSeeder::class);
        $this->call(PasswordResetsTableSeeder::class);
        $this->call(PaymentRequestsTableSeeder::class);
        $this->call(PharmacyItemDetailsTableSeeder::class);
        $this->call(PhoneVerificationsTableSeeder::class);
        $this->call(ProvideDMEarningsTableSeeder::class);
        $this->call(ReactTestimonialsTableSeeder::class);
        $this->call(RefundsTableSeeder::class);
        $this->call(RefundReasonsTableSeeder::class);
        $this->call(ReviewsTableSeeder::class);
        $this->call(SocialMediaTableSeeder::class);
        $this->call(SoftCredentialsTableSeeder::class);
        $this->call(StoresTableSeeder::class);
        $this->call(StoreConfigsTableSeeder::class);
        $this->call(StoreScheduleTableSeeder::class);
        $this->call(StoreWalletsTableSeeder::class);
        $this->call(TagsTableSeeder::class);
        $this->call(TempProductsTableSeeder::class);
        $this->call(TrackDeliverymenTableSeeder::class);
        $this->call(TranslationsTableSeeder::class);
        $this->call(UnitsTableSeeder::class);
        $this->call(UsersTableSeeder::class);
        $this->call(UserInfosTableSeeder::class);
        $this->call(UserNotificationsTableSeeder::class);
        $this->call(VendorsTableSeeder::class);
        $this->call(VendorEmployeesTableSeeder::class);
        $this->call(WalletBonusesTableSeeder::class);
        $this->call(WalletPaymentsTableSeeder::class);
        $this->call(WalletTransactionsTableSeeder::class);
        $this->call(WebsocketsStatisticsEntriesTableSeeder::class);
        $this->call(WishlistsTableSeeder::class);
        $this->call(WithdrawalMethodsTableSeeder::class);
        $this->call(WithdrawRequestsTableSeeder::class);
        $this->call(ZonesTableSeeder::class);
    }
}
